In [2]:
import numpy as np

In [3]:
#array of 10 ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
#array of int 10 to 50
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [6]:
# 3X3 mat val 0 to 8
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
#5X5 identity mat
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [8]:
#numpy to multiply 2 MAT

In [9]:
mat1 = ([1,6,5],[3,4,8],[2,12,3])
mat2 = ([3,4,6],[5,6,7],[6,56,7])

In [10]:
result = np.dot(mat1,mat2)

In [11]:
print(result)

[[ 63 320  83]
 [ 77 484 102]
 [ 84 248 117]]
